version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    environment:
      FLASK_APP: "flaskr:create_app"
      FLASK_DEBUG: "True"
      FLASK_RUN_PORT: "5000"
      FLASK_RUN_HOST: "0.0.0.0"
      FLASK_SECRET_KEY: "dev"
      FLASK_DATABASE_URL: "sqlite:///flaskr.sqlite"
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - .:/app/
