# syntax=docker/dockerfile:1
FROM python:3.8.16-slim-buster

RUN pip install poetry
WORKDIR /app
COPY poetry.lock pyproject.toml /app/
RUN poetry config virtualenvs.create false && poetry install --no-root
COPY . /app/

CMD ["flask", "run"]
