# syntax=docker/dockerfile:1
FROM python:3.8.16-slim-buster

RUN apt-get update \
  && apt-get -y install libpq-dev gcc netcat \
  && pip install poetry

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY poetry.lock pyproject.toml /app/

RUN poetry config virtualenvs.create false \
  && poetry install --no-root

COPY . /app/

ENTRYPOINT ["/app/entrypoint.sh"]
